services:
  torchlight:
    build:
      context: .
      dockerfile: Dockerfileu
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY: ${NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY}
        NEXT_PUBLIC_ANTHROPIC_KEY: ${NEXT_PUBLIC_ANTHROPIC_KEY}
        NEXT_PUBLIC_ANTHROPIC_MODEL: ${NEXT_PUBLIC_ANTHROPIC_MODEL}
        NEXT_PUBLIC_OPEN_AI_TOKEN: ${NEXT_PUBLIC_OPEN_AI_TOKEN}
        NEXT_PUBLIC_OPEN_AI_MODEL: ${NEXT_PUBLIC_OPEN_AI_MODEL}
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY=${NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY}
      - NEXT_PUBLIC_ANTHROPIC_KEY=${NEXT_PUBLIC_ANTHROPIC_KEY}
      - NEXT_PUBLIC_ANTHROPIC_MODEL=${NEXT_PUBLIC_ANTHROPIC_MODEL}
      - NEXT_PUBLIC_OPEN_AI_TOKEN=${NEXT_PUBLIC_OPEN_AI_TOKEN}
      - NEXT_PUBLIC_OPEN_AI_MODEL=${NEXT_PUBLIC_OPEN_AI_MODEL}
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    env_file:
      - .env